### ISSUE TITLE
CPHD does not read 16 bit integer types without a scale factor.

### ISSUE THREAD

**Issue by clydestanfield** [ngageoint/six-library#115]
From Matthew Dellinger 10/4/2016

I'm attempting to write a method that will take any CPHD file and return complex float data with scales (if any) applied. When I attempt to use the cphd::Wideband::read method that applies scaling, it works correctly for all floating point files (with and without scaling) and for 8-bit and 16-bit integer data with scaling. However, 
I've got a 16-bit integer CPHD file that was created without any scaling. When I run this file through, the const mem::BufferViewstd::complex<float >& data argument is filled with integer data, rather than floating point data.

This is occurring because in at Wideband.cpp:403, we take the else branch (we don't need to scale), so we read the (integer) data into the output buffer, byteswap it, and then return it to the user. The result is a buffer typed as complex float that is 50% full of complex 16-bit integer data, and 50% uninitialized. For floating point data, this codepath works fine, since the data is already formatted as complex float.

We're currently working around this by using 1.0 + DBL_EPSILON as a constant scale for all reads if the data is unscaled and the type isn't float. That ensures that we always go down the scaling path, but isn't significant enough to change our data in any meaningful way.

I'm not sure what the proper behavior for this method is. Perhaps the method should either upscale the data to float or throw an error? The simplest solution would be to change line 403 from

if (needToScale)

to 

// We can only directly read data that is already complex float
if (needToScale && mElementSize != 8)

Which would force all reads that needed promoted to float through the scaling path. That would take a slight performance hit for unscaled integer data, because you'd be doing an extra per-sample lookup and multiply by 1. If you want, I can work up a patch for a third else if case that would call a byteSwapAndPromote() function that would do the type promotion without the scaling.

**Comment by asylvest** [comment]
Fixed in #131
