### ISSUE TITLE
Example product in SIX compatible formats?

### ISSUE THREAD

**Issue by piyushrpt** [ngageoint/six-library#192]
Hi,
    Is there an archive of example products generate using SIX/SICD/SIDD? I'm interested in finding workingexamples that converts data from current missions like TerraSAR-X, COSMO-SkyMed, Sentinel-1 or Radarsat-2 into one of the SIX compatible formats. In particular, I'm interested in using Level-1 SLC products for interferometric applications and in evaluating the completeness of metadata fields for such applications. 

Piyush

**Comment by asylvest** [comment]
There is a sample SICD from a public TerraSAR-X collect at https://github.com/ngageoint/six-library/wiki/Sample-SICDs.  A lot of the issues posting more datasets are related to what's publicly available and/or ITAR concerns.

**Comment by khavernathy** [comment]
Are there SIX-compatible CPHD or CPHD03 files anywhere?

When I use some of the `.../cphd03/tests` executables on files I have, I get `Unknown exception`.

**Comment by JonathanMeans** [comment]
I'm looking into more samples that could be made available.

In the mean time, if you can share what you have I might be able to dig into the error.
