### ISSUE TITLE
Include schemas in CSM package

### ISSUE THREAD

**Issue by johnpdpkarp** [ngageoint/six-library#277]
If one builds the CSM plugin from the source code, it can't be used without the availability of the schema files.   It would be very helpful for these to be included here.

**Comment by asylvest** [comment]
The schemas are checked into the repo:
* https://github.com/ngageoint/six-library/tree/master/six/modules/c%2B%2B/six.sicd/conf/schema
* https://github.com/ngageoint/six-library/tree/master/six/modules/c%2B%2B/six.sidd/conf/schema

If you do a `waf install --target=six-csm` (or just a `waf install` to install everything), the schemas are installed in `<install dir>/conf/schema/six`

**Comment by johnpdpkarp** [comment]
Thanks!
