### ISSUE TITLE
Erroneous plugin path warning

### ISSUE THREAD

**Issue by JonathanMeans** [ngageoint/six-library#335]
If you run `round_trip_six` from a clean build without the `NITF_PLUGIN_PATH` environment variable set, you get this warning:

    Warning: Unable to find plugin path.
    Specify plugin location by setting environment variable NITF_PLUGIN_PATH, or by building the library from source

This is misleading. SIX builds the NITRO plugins statically, so it doesn't matter whether it can find the (dynamic) plugins directory.

**Comment by JDanielSmith** [comment]
Fixed in **develop/jdsmith**
