### ISSUE TITLE
Documentation for CPHD specification

### ISSUE THREAD

**Issue by CobaltGray** [ngageoint/six-library#35]
Hi,
Is there a copy of the CPHD interface control document ? or something that explains the format of the CPHD file please?

**Comment by asylvest** [comment]
There is a CPHD spec but I am not sure if it has been approved for public release or not.  If you send me your email address I can work with you to see if we can provide access or refer you to someone who can.

**Comment by bradh** [comment]
The spec and schema are public:  https://nsgreg.nga.mil/NSGDOC/files/doc/Document/NGA.STND.0068-1_1.0.1_CPHD.pdf and https://nsgreg.nga.mil/NSGDOC/files/doc/Document/CPHD_schema_V1.0.1_2018_05_21.xsd
