### ISSUE TITLE
CPHD writer does not allow classification or release information

### ISSUE THREAD

**Issue by clydestanfield** [ngageoint/six-library#50]
The CPHD writer internally creates a FileHeader object and uses that when writing to disk. This means a user does not have an opportunity to fill out the classification and release information. An override should be created that allows the user to pass in a filled out FileHeader and use that instead.

**Comment by asylvest** [comment]
I think the cleanest way to do this is to add two optional string inputs to the writeMetadata() overloading that takes in the pathname and ripple down.  If the string is non-empty, set the FileHeader with that value.  Also while you're in there, fix the `vmb` typos in CPHDWriter.cpp (should be `vbm`).

**Comment by asylvest** [comment]
Fixed in #51
