### ISSUE TITLE
Polarizations of "UNKNOWN" not supported

### ISSUE THREAD

**Issue by bombaci-vsc** [ngageoint/six-library#55]
Parsing SICD XML containing polarizations of 'UNKNOWN' cause an "Unsupported conversion" exception.  I first ran into this at [DualPolarizationType six::toType<DualPolarizationType>()](https://github.com/ngageoint/six-library/blob/3f0a57bcfe4e5c3bda77a4cf3a4d5fef679d234f/six/modules/c%2B%2B/six/source/Utilities.cpp#L530), but skimming through the code it looks like 'UNKNOWN' is missing from most of the various polarization routines.

**Comment by asylvest** [comment]
Thanks for pointing this out.  FYI, this is mostly fixed under #58... should have it merged to master tomorrow.

**Comment by asylvest** [comment]
Resolved under #58 and merged to master - let us know if this doesn't resolve your issue.
