### ISSUE TITLE
Provide redistributable sample data

### ISSUE THREAD

**Issue by bradh** [ngageoint/six-library#61]
Ideally there would be sample data that allowed wider understanding of SICD. Possibly it could be synthesised from redistributable data in the AFRL data sets (https://www.sdms.afrl.af.mil/).

**Comment by asylvest** [comment]
@bradh we'll start gradually putting some samples from public data at https://github.com/ngageoint/six-library/wiki/Sample-SICDs.  For now we've updated with one SICD XML that was generated by converting a public TSX dataset.  If you are interested in the full SICD NITF, not just the XML, we will have to figure out a spot to host the files.

**Comment by bradh** [comment]
Thanks for looking at this, and adding the XML. I was hoping for the NITF (in the longer term), but this is still a big head-start.

**Comment by asylvest** [comment]
@bradh I've got a spot to host the files now... take a look at the wiki again.  It now contains links to the XML and actual SICD NITF.  We'll add additional examples here down the road as we get a chance.

**Comment by bradh** [comment]
Looks good, and is much appreciated.

I'm happy for this issue to be closed, or kept open, whatever works for you.
