### ISSUE TITLE
SIDD 2.0.0 reading fails if no LUT present

### ISSUE THREAD

**Issue by bombaci-vsc** [ngageoint/six-library#674]
SIX fails to read a SIDD 2.0.0 NITF if the Image Sub-Header doesn't contain a LUT.

An example SIDD can be found in the Umbra open data.
https://radiantearth.github.io/stac-browser/#/external/s3.us-west-2.amazonaws.com/umbra-open-data-catalog/stac/2023/2023-01/2023-01-20/433739b5-5f0d-403b-baba-651e897fc2d7/433739b5-5f0d-403b-baba-651e897fc2d7.json?.language=en&.asset=asset-SIDD

The error seems to be caused by a combination of: 
1. NitfReadControl.cpp [always trying to read a LUT](https://github.com/ngageoint/six-library/blob/SIX-3.2.2/six/modules/c%2B%2B/six/source/NITFReadControl.cpp#L458-L465) .
```c++
        // SIDD 2.0 needs to read LUT directly from NITF
        const auto pData = currentInfo->getData();
        if (pData->getDataType() == DataType::DERIVED && pData->getVersion() == "2.0.0")
        {
            const auto nitfLut = subheader.getBandInfo(0).getLookupTable();
            currentInfo->getData_()->setDisplayLUT(std::make_unique<AmplitudeTable>(nitfLut));
        }
```

2. getLookupTable() [returning 0 tables of length 0](https://github.com/ngageoint/six-library/blob/SIX-3.2.2/externals/nitro/modules/c%2B%2B/nitf/source/BandInfo.cpp#L103-L104)  when a LUT isn't present.
```c++
        //we'll create one - there's no harm in doing it
        getNativeOrThrow()->lut = nitf_LookupTable_construct(0, 0, &error);
```

3. and AmplitudeTable [requiring a table to be of size 256](https://github.com/ngageoint/six-library/blob/SIX-3.2.2/six/modules/c%2B%2B/six/include/six/Types.h#L412-L415).
```c++
        if (size() != 256)
        {
            throw std::invalid_argument("lookupTable should have 256 elements.");
        }
```

It isn't obvious why NitfReadControl is trying to aways read a LUT for SIDD 2.0.0.  The NITF File Format Description Document ([NGA.STND.0025-2](https://nsgreg.nga.mil/doc/view?i=4907&month=7&day=13&year=2023)) has a table which specifies when LUTs should be present.  (Pages 16-17, I've edited out the page break)
![image](https://github.com/ngageoint/six-library/assets/14338439/5c5c9033-795e-4e67-b8d6-733e2535eecd)

I interpret the table to say that `MONO8I`, `MONO16I`, and `SI` should not have LUTs in the Sub-Header.

**Comment by JDanielSmith** [comment]
See https://github.com/ngageoint/six-library/pull/683
