### ISSUE TITLE
Issue with trying to build six 3.2.4, "numpyutils/AutoPtr.h" not found

### ISSUE THREAD

**Issue by wilsonjohnpatCO** [ngageoint/six-library#698]
I am trying to build six-library 3.2.4.   I am getting the error that "numpyutils/AutoPtr.h" is not found when compiling six-library-SIX-3.2.4/six/modules/python/six.sicd/source/generated/six_sicd_wrap.cxx    

I gather that this header would be part of coda-oss, but I am not finding it as part of the included coda-oss.

**Comment by JDanielSmith** [comment]
https://github.com/mdaus/coda-oss/pull/722
