### ISSUE TITLE
Switch AmpSF and TropoSRP in CPHD XML

### ISSUE THREAD

**Issue by dstarinshak** [ngageoint/six-library#92]
In the CPHD XML, TropoSRP is supposed to come before AmpSF. The VectorParameters section of the XML string has them in the incorrect order.

Simple fix: in CPHDXMLControl.cpp:Line445, switch the block of code dealing with the AmpSF size with the following block for the TropoSRP size.

**Comment by asylvest** [comment]
Double-checked SIX and talked with @dstarinshak and the SIX implementation is actually correct.  The way the CPHD 0.3 spec is defined, the order in the actual binary vector based parameters section (defined in Table 2-2) is TropoSRP followed by AmpSF.  In the XML, the CPHD.VectorParameters section that tells you what fields are present in the binary VPM (Table 3.7) specifies the order as AmpSF followed by TropoSRP.

While this is unfortunately not a consistent order between the two, it is the way the spec defines the fields and the SIX readers are writers account for this.
